version: '3'
services:
  go:  
    container_name: go-gemmails
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
  database:
    container_name: postgres-gemmails
    image: postgres:10.3
    restart: always
    volumes:
      - pgdata:/var/lib/postgres
    environment:
        - POSTGRES_DB=gemmails
        - POSTGRES_USER=gem
        - POSTGRES_PASSWORD=secret
    ports:
        - 54320:5432
  redis:
    container_name: redis-gemmails
    image: redis
    ports:
      - 6379:6379
volumes:
  pgdata: